import type { RoleCForRoleDResult } from "../../../role-d-integration/contracts"
import type { RoleDSession } from "../domain/types"

export const nextRoundHandoff = {
  status: "ready",
  runId: "RUN-NEXT",
  learningSession: {
    phase: "anchor_pending",
    sessionId: "C-SESSION-NEXT",
    formId: "FORM-NEXT",
    attemptNo: 1,
    profileVersion: "PROFILE-NEXT",
    pathNodeId: "PATH-NEXT",
    targetSourceIds: ["K007"],
    routingRequestId: "ROUTING-NEXT",
    requiredItemIds: ["NEXT-I1"],
  },
  deliveryToD: {
    reviewedRelease: {
      schema_version: "1.0",
      delivery_kind: "reviewed_release",
      delivery_id: "DELIVERY-RELEASE-NEXT",
      status: "accepted",
    },
    learningSession: {
      schema_version: "1.0",
      delivery_kind: "learning_session",
      delivery_id: "DELIVERY-SESSION-NEXT",
      status: "accepted",
    },
  },
  artifacts: [
    {
      id: "LESSON-NEXT",
      kind: "lesson",
      title: "下一轮循环讲义",
      status: "real",
      content: "下一轮继续练习 for 循环。",
      options: [],
      items: [],
      citations: [{ source_id: "K007", fact_id: "F001" }],
    },
    {
      id: "LAB-NEXT",
      kind: "lab",
      title: "下一轮循环实验",
      status: "real",
      content: "for value in values:\n    pass",
      options: [],
      items: [],
      citations: [{ source_id: "K007", fact_id: "F001" }],
    },
    {
      id: "ASSESSMENT-NEXT",
      kind: "assessment",
      title: "下一轮锚点测评",
      status: "real",
      content: "先完成公开锚点题。",
      options: ["opt_iterate", "opt_install"],
      items: [{
        id: "NEXT-I1",
        tier: 1,
        modality: "mcq",
        prompt: "for 循环适合做什么？",
        options: ["遍历序列", "安装依赖"],
        option_ids: ["opt_iterate", "opt_install"],
        citations: [{ source_id: "K007", fact_id: "F001" }],
      }],
      citations: [{ source_id: "K007", fact_id: "F001" }],
    },
  ],
  workflow: [{
    id: "NEXT-C1",
    agent: "concept-tutor",
    stage: "下一轮定制讲义",
    status: "completed",
    summary: "下一轮内容已通过审核。",
    timestamp: "刚刚",
  }],
} satisfies Extract<RoleCForRoleDResult, { status: "ready" }>

export function completedRoleDSession(): RoleDSession {
  return {
    version: 1,
    eventMode: "live",
    sessionId: "D-PLAN-SESSION",
    updatedAt: "2026-07-30T00:00:00.000Z",
    profile: {
      learnerId: "learner-1",
      level: "basic",
      knownConcepts: ["变量"],
      weakConcepts: ["循环"],
      goal: "完成成绩统计程序",
    },
    conflicts: [],
    retrieval: {
      query: "循环",
      topK: 1,
      items: [{
        sourceId: "K007",
        title: "for 循环",
        difficulty: "beginner",
        score: 10,
        reason: "命中循环",
        snippet: "for 循环用于遍历序列",
        file: "K007_for_loop.md",
        facts: [{
          sourceId: "K007",
          factId: "F001",
          content: "for 循环用于遍历序列",
        }],
        examples: [],
        practiceTasks: [],
        quizItems: [],
        trace: {
          matchedKeywords: ["循环"],
          matchedFields: ["keywords"],
          difficultyMatch: true,
          scoreBreakdown: {
            keyword: 10,
            title: 0,
            facts: 0,
            practiceTasks: 0,
            difficulty: 0,
            bonus: 0,
          },
        },
      }],
    },
    artifacts: [{
      id: "ASSESSMENT-CURRENT",
      kind: "assessment",
      title: "本轮测评",
      status: "real",
      content: "本轮公开题面",
      options: ["A", "B"],
      items: [{
        id: "CURRENT-I1",
        tier: 1,
        modality: "mcq",
        prompt: "本轮题目",
        options: ["A", "B"],
        optionIds: ["A", "B"],
        citations: [{ sourceId: "K007", factId: "F001" }],
      }],
      citations: [{ sourceId: "K007", factId: "F001" }],
      evidenceStatus: "grounded",
    }],
    roleC: {
      runId: "RUN-CURRENT",
      learningSessionId: "C-SESSION-CURRENT",
      formId: "FORM-CURRENT",
      attemptNo: 1,
      profileVersion: "PROFILE-CURRENT",
      pathNodeId: "PATH-CURRENT",
      targetSourceIds: ["K007"],
      routing: {
        phase: "route_locked",
        routingRequestId: "ROUTING-CURRENT",
        routeLockId: "LOCK-CURRENT",
        routeId: "ROUTE-CURRENT",
        action: "reinforce",
        anchorScoreRatio: 0.5,
        anchorItemIds: ["CURRENT-I1"],
        requiredItemIds: ["CURRENT-I1"],
      },
    },
    feedback: {
      feedbackId: "FEEDBACK-CURRENT",
      submissionId: "SUBMISSION-CURRENT",
      learnerId: "learner-1",
      profileVersion: "PROFILE-CURRENT",
      pathNodeId: "PATH-CURRENT",
      roundScore: {
        rawScore: 0.6,
        maxScore: 1,
        accuracy: 0.6,
        evidenceScore: 0.8,
      },
      objectiveResults: [],
      itemResults: [],
      masterySnapshot: [],
      finalDecision: {
        action: "reinforce",
        basis: "round_accuracy",
        confidence: 0.8,
        reasonCodes: ["reinforcement_band"],
        targetObjectiveIds: ["O1"],
        policyRef: "role-c-round-accuracy-v1",
      },
      feedbackSummary: "本轮需要继续巩固。",
    },
    evidenceGaps: [],
    workflow: [{
      id: "CURRENT-C1",
      agent: "tiered-evaluator",
      stage: "本轮正式评分",
      status: "completed",
      summary: "本轮评分完成。",
      timestamp: "刚刚",
    }],
    path: [{
      id: "K007",
      title: "for 循环",
      difficulty: "beginner",
      status: "current",
      reason: "当前学习节点",
    }],
    decision: {
      next: "reinforce",
      reason: "本轮需要继续巩固。",
    },
    assessmentGraded: true,
    planSource: "real-ab",
    planInput: {
      learnerId: "learner-1",
      educationContext: "测试",
      timeBudget: "每周 2 小时",
      priorLanguages: [],
      knownConcepts: ["变量"],
      weakConcepts: ["循环"],
    },
    diagnosis: {
      sourceId: "K007",
      factId: "F001",
      concept: "for 循环",
      difficulty: "beginner",
      question: "for 循环适合什么？",
      options: ["遍历序列", "安装依赖"],
      answer: "遍历序列",
    },
    view: {
      currentStage: "feedback",
      maxUnlockedStage: "feedback",
      activeArtifactKind: "assessment",
      selectedSourceId: "K007",
      remediationStarted: false,
      goalDraft: "完成成绩统计程序",
      selfRatingDraft: "basic",
      diagnosisAnswer: "遍历序列",
      diagnosisSubmitted: true,
      assessmentAnswers: { "CURRENT-I1": "A" },
      assessmentSubmitted: true,
      assessmentStatus: "completed",
      assessmentMessage: "本轮需要继续巩固。",
      detailDrawer: "none",
    },
  }
}

export function publishedContinuationResponse() {
  return {
    status: "published",
    preparation: {
      status: "generation_ready",
      action: "reinforce",
      generation_action: "reinforce",
      prior_feedback_ref: "FEEDBACK-CURRENT",
      run_id: "RUN-NEXT",
      profile_version: "PROFILE-NEXT",
      path_node_id: "PATH-NEXT",
    },
    generation: {
      pipeline_status: "ready",
      pipeline_state: "READY",
    },
    learning_session: {
      phase: "anchor_pending",
      routing_request_id: "ROUTING-NEXT",
      session_id: "C-SESSION-NEXT",
      run_id: "RUN-NEXT",
      form_id: "FORM-NEXT",
      attempt_no: 1,
      required_item_ids: ["NEXT-I1"],
    },
    delivery_to_d: {
      reviewed_release: nextRoundHandoff.deliveryToD.reviewedRelease,
      learning_session: nextRoundHandoff.deliveryToD.learningSession,
    },
    role_d_handoff: nextRoundHandoff,
  }
}
