import type { KnowledgeBase } from "./types"

export const MODERN_AI_KNOWLEDGE_BASE: KnowledgeBase = {
  module: "现代人工智能基础",
  version: "0.1.0",
  updatedAt: "2026-08-05",
  sources: ["KnowBalance 自编教学切片", "教师指定 AI 培训方向"],
  items: [
    {
      sourceId: "AI001",
      title: "人工智能、机器学习与深度学习",
      module: "现代人工智能基础",
      difficulty: "beginner",
      file: "knowledge_base/modern_ai/AI001_ai_ml_dl.md",
      snippet: "人工智能是让机器表现出智能行为的技术领域。",
      prerequisites: [],
      keywords: ["人工智能", "机器学习", "深度学习", "生成式AI", "AI", "ML", "DL"],
      facts: [
        { sourceId: "AI001", factId: "F001", source_id: "AI001", fact_id: "F001", content: "人工智能是让机器表现出智能行为的技术领域。" },
        { sourceId: "AI001", factId: "F002", source_id: "AI001", fact_id: "F002", content: "机器学习是人工智能中的一类方法，核心是让模型从数据中学习规律。" },
        { sourceId: "AI001", factId: "F003", source_id: "AI001", fact_id: "F003", content: "深度学习通常使用多层神经网络从数据中学习表示。" },
      ],
      examples: [{ title: "区分 AI、ML、DL", code: "concepts = [\"AI\", \"ML\", \"DL\"]\nfor concept in concepts:\n    print(concept)", explanation: "AI 是更大的领域，ML 是 AI 的方法之一，DL 是常见的 ML 技术路线之一。" }],
      practiceTasks: ["用自己的话说明 AI、ML、DL 的层级关系", "判断一个垃圾邮件分类器属于 AI、ML 还是 DL 应用"],
      quizItems: [
        { level: 1, type: "choice", question: "机器学习的核心特征是什么？", options: ["从数据中学习规律", "只靠人工写死规则", "只能处理图像", "只能生成文本"], answer: "从数据中学习规律", sourceId: "AI001", factId: "F002" },
        { level: 2, type: "short_answer", question: "说明人工智能、机器学习、深度学习三者的包含关系。", answer: "人工智能是大领域，机器学习是其中一类方法，深度学习通常是基于多层神经网络的机器学习方法。", sourceId: "AI001", factId: "F003" },
        { level: 2, type: "debugging", question: "判断正误：深度学习等同于所有人工智能。", answer: "错误。深度学习是人工智能中的一种技术路线，不等同于全部人工智能。", sourceId: "AI001", factId: "F001" },
        { level: 3, type: "practice", question: "给出一个日常 AI 应用，并说明它可能用到机器学习的哪一部分思想。", answer: "能指出应用场景，并说明从数据中学习规律的思想。", sourceId: "AI001", factId: "F002" },
      ],
    },
    {
      sourceId: "AI002",
      title: "数据集、特征与标签",
      module: "现代人工智能基础",
      difficulty: "beginner",
      file: "knowledge_base/modern_ai/AI002_dataset_feature_label.md",
      snippet: "数据集是用于训练、验证或测试模型的数据集合。",
      prerequisites: ["AI001"],
      keywords: ["数据集", "特征", "标签", "样本", "训练数据", "测试数据"],
      facts: [
        { sourceId: "AI002", factId: "F001", source_id: "AI002", fact_id: "F001", content: "数据集是用于训练、验证或测试模型的数据集合。" },
        { sourceId: "AI002", factId: "F002", source_id: "AI002", fact_id: "F002", content: "特征是描述样本的输入信息。" },
        { sourceId: "AI002", factId: "F003", source_id: "AI002", fact_id: "F003", content: "标签是监督学习中模型需要预测的目标结果。" },
      ],
      examples: [{ title: "成绩预测数据", code: "sample = {\"hours\": 3, \"attendance\": 0.9, \"passed\": True}\nfeatures = [sample[\"hours\"], sample[\"attendance\"]]\nlabel = sample[\"passed\"]\nprint(features, label)", explanation: "学习时长和出勤率可作为特征，是否通过可作为标签。" }],
      practiceTasks: ["为垃圾邮件识别任务列出 3 个可能特征", "判断房价预测任务中的标签是什么"],
      quizItems: [
        { level: 1, type: "choice", question: "监督学习中模型要预测的目标通常叫作什么？", options: ["标签", "注释", "变量名", "索引"], answer: "标签", sourceId: "AI002", factId: "F003" },
        { level: 2, type: "short_answer", question: "在学生成绩预测中，学习时长可以作为特征还是标签？为什么？", answer: "可以作为特征，因为它是描述样本的输入信息。", sourceId: "AI002", factId: "F002" },
        { level: 2, type: "debugging", question: "判断正误：训练数据里任何字段都一定是标签。", answer: "错误。特征是输入信息，标签才是要预测的目标结果。", sourceId: "AI002", factId: "F003" },
        { level: 3, type: "practice", question: "为“预测学生是否通过考试”设计 3 个特征和 1 个标签。", answer: "能给出学习时长、出勤率、历史成绩等特征，并以是否通过作为标签。", sourceId: "AI002", factId: "F001" },
      ],
    },
    {
      sourceId: "AI003",
      title: "训练集、测试集与过拟合",
      module: "现代人工智能基础",
      difficulty: "basic",
      file: "knowledge_base/modern_ai/AI003_train_test_overfit.md",
      snippet: "训练集用于拟合模型，测试集用于评估模型在未见数据上的表现。",
      prerequisites: ["AI002"],
      keywords: ["训练集", "测试集", "验证集", "过拟合", "泛化", "评估"],
      facts: [
        { sourceId: "AI003", factId: "F001", source_id: "AI003", fact_id: "F001", content: "训练集用于拟合模型。" },
        { sourceId: "AI003", factId: "F002", source_id: "AI003", fact_id: "F002", content: "测试集用于评估模型在未见数据上的表现。" },
        { sourceId: "AI003", factId: "F003", source_id: "AI003", fact_id: "F003", content: "过拟合是指模型过度记住训练数据而在新数据上表现变差。" },
      ],
      examples: [{ title: "划分训练和测试样本", code: "data = list(range(10))\ntrain = data[:8]\ntest = data[8:]\nprint(\"train\", train)\nprint(\"test\", test)", explanation: "训练样本用于学习规律，测试样本用于检查模型面对新样本的表现。" }],
      practiceTasks: ["解释为什么不能只看训练集准确率", "举例说明过拟合的表现"],
      quizItems: [
        { level: 1, type: "choice", question: "测试集的主要用途是什么？", options: ["评估未见数据表现", "保存代码", "替代标签", "删除特征"], answer: "评估未见数据表现", sourceId: "AI003", factId: "F002" },
        { level: 2, type: "short_answer", question: "为什么训练集准确率很高不一定代表模型好？", answer: "模型可能过拟合，过度记住训练数据，在新数据上表现变差。", sourceId: "AI003", factId: "F003" },
        { level: 2, type: "debugging", question: "判断正误：模型在训练集上 100% 正确，就一定能在新数据上 100% 正确。", answer: "错误。训练集表现不能替代测试集泛化评估。", sourceId: "AI003", factId: "F002" },
        { level: 3, type: "practice", question: "给定 100 条样本，设计一个简单的训练集/测试集划分方案。", answer: "可将 80 条作为训练集、20 条作为测试集，并说明测试集用于未见数据评估。", sourceId: "AI003", factId: "F001" },
      ],
    },
    {
      sourceId: "AI004",
      title: "分类、回归与聚类任务",
      module: "现代人工智能基础",
      difficulty: "basic",
      file: "knowledge_base/modern_ai/AI004_ml_tasks.md",
      snippet: "分类任务预测离散类别，回归任务预测连续数值。",
      prerequisites: ["AI002"],
      keywords: ["分类", "回归", "聚类", "预测", "类别", "连续数值"],
      facts: [
        { sourceId: "AI004", factId: "F001", source_id: "AI004", fact_id: "F001", content: "分类任务预测离散类别。" },
        { sourceId: "AI004", factId: "F002", source_id: "AI004", fact_id: "F002", content: "回归任务预测连续数值。" },
        { sourceId: "AI004", factId: "F003", source_id: "AI004", fact_id: "F003", content: "聚类任务把样本按相似性分组，通常不依赖人工给定标签。" },
      ],
      examples: [{ title: "任务类型判断", code: "tasks = {\"垃圾邮件识别\": \"分类\", \"房价预测\": \"回归\", \"用户分群\": \"聚类\"}\nfor name, kind in tasks.items():\n    print(name, kind)", explanation: "不同任务的输出形式决定了它属于分类、回归还是聚类。" }],
      practiceTasks: ["判断成绩等级预测属于分类还是回归", "说明用户分群为什么常被视为聚类任务"],
      quizItems: [
        { level: 1, type: "choice", question: "预测房屋价格通常属于哪类任务？", options: ["回归", "分类", "聚类", "排序"], answer: "回归", sourceId: "AI004", factId: "F002" },
        { level: 2, type: "short_answer", question: "垃圾邮件识别为什么通常是分类任务？", answer: "因为它预测的是垃圾/非垃圾等离散类别。", sourceId: "AI004", factId: "F001" },
        { level: 2, type: "debugging", question: "判断正误：聚类任务一定需要每个样本都有人工标签。", answer: "错误。聚类通常按相似性分组，不依赖人工给定标签。", sourceId: "AI004", factId: "F003" },
        { level: 3, type: "practice", question: "分别给出一个分类、回归、聚类的教育场景例子。", answer: "能区分离散类别、连续数值和相似性分组三类输出。", sourceId: "AI004", factId: "F001" },
      ],
    },
    {
      sourceId: "AI005",
      title: "大语言模型、提示词与 RAG",
      module: "现代人工智能基础",
      difficulty: "intermediate",
      file: "knowledge_base/modern_ai/AI005_llm_prompt_rag.md",
      snippet: "大语言模型根据上下文生成文本，但可能产生不受证据支持的幻觉内容。",
      prerequisites: ["AI001", "AI002"],
      keywords: ["大语言模型", "LLM", "提示词", "prompt", "RAG", "检索增强生成", "幻觉", "上下文"],
      facts: [
        { sourceId: "AI005", factId: "F001", source_id: "AI005", fact_id: "F001", content: "大语言模型根据上下文生成文本。" },
        { sourceId: "AI005", factId: "F002", source_id: "AI005", fact_id: "F002", content: "RAG 通过检索外部知识为生成过程提供证据。" },
        { sourceId: "AI005", factId: "F003", source_id: "AI005", fact_id: "F003", content: "幻觉是指模型生成了不受可靠证据支持的内容。" },
      ],
      examples: [{ title: "RAG 证据先行", code: "evidence = \"Python 使用 = 进行变量赋值。\"\nquestion = \"Python 如何给变量赋值？\"\nanswer = evidence\nprint(answer)", explanation: "先检索证据，再围绕证据生成回答，可以降低无依据生成。" }],
      practiceTasks: ["写一个提示词，要求回答必须引用给定证据", "判断一段回答是否包含无证据支持的内容"],
      quizItems: [
        { level: 1, type: "choice", question: "RAG 的核心作用是什么？", options: ["为生成提供外部证据", "删除所有数据", "只做图像处理", "替代编程语言"], answer: "为生成提供外部证据", sourceId: "AI005", factId: "F002" },
        { level: 2, type: "short_answer", question: "什么是大语言模型幻觉？", answer: "模型生成了不受可靠证据支持的内容。", sourceId: "AI005", factId: "F003" },
        { level: 2, type: "debugging", question: "判断正误：只要用了大语言模型，生成内容就一定完全正确。", answer: "错误。大语言模型可能生成幻觉，需要证据和审核。", sourceId: "AI005", factId: "F003" },
        { level: 3, type: "practice", question: "设计一个 RAG 问答流程，说明检索、生成、审核三步分别做什么。", answer: "能说明先检索证据，再生成回答，最后检查回答是否被证据支持。", sourceId: "AI005", factId: "F002" },
      ],
    },
    {
      sourceId: "AI006",
      title: "多智能体协作与事实审核",
      module: "现代人工智能基础",
      difficulty: "intermediate",
      file: "knowledge_base/modern_ai/AI006_multi_agent_audit.md",
      snippet: "多智能体系统通过职责分工让不同 Agent 执行诊断、生成、审核和决策。",
      prerequisites: ["AI005"],
      keywords: ["多智能体", "Agent", "协作", "事实审核", "角色分工", "辩论", "纠偏"],
      facts: [
        { sourceId: "AI006", factId: "F001", source_id: "AI006", fact_id: "F001", content: "多智能体系统通过职责分工让不同 Agent 执行不同任务。" },
        { sourceId: "AI006", factId: "F002", source_id: "AI006", fact_id: "F002", content: "事实审核 Agent 用于检查生成内容是否受到证据支持。" },
        { sourceId: "AI006", factId: "F003", source_id: "AI006", fact_id: "F003", content: "生成、审核和决策分离可以降低单一生成模块直接发布错误内容的风险。" },
      ],
      examples: [{ title: "Agent 分工示例", code: "agents = [\"诊断Agent\", \"生成Agent\", \"审核Agent\", \"决策Agent\"]\nfor agent in agents:\n    print(agent)", explanation: "不同 Agent 分别负责学情诊断、内容生成、事实审核和下一步学习决策。" }],
      practiceTasks: ["设计一个三 Agent 教学流程", "说明为什么生成和审核应该分离"],
      quizItems: [
        { level: 1, type: "choice", question: "事实审核 Agent 的主要职责是什么？", options: ["检查生成内容是否有证据支持", "随机删除知识库", "只负责界面配色", "替代所有学习者输入"], answer: "检查生成内容是否有证据支持", sourceId: "AI006", factId: "F002" },
        { level: 2, type: "short_answer", question: "为什么多智能体系统要做角色分工？", answer: "角色分工能让不同 Agent 执行诊断、生成、审核和决策等不同任务。", sourceId: "AI006", factId: "F001" },
        { level: 2, type: "debugging", question: "判断正误：生成 Agent 生成内容后不需要审核就可以直接发布。", answer: "错误。生成内容需要事实审核，避免无证据或错误内容直接发布。", sourceId: "AI006", factId: "F002" },
        { level: 3, type: "practice", question: "为个性化教学平台设计“诊断-生成-审核-决策”四步 Agent 协作流程。", answer: "能说明诊断学习者、生成资源、审核事实、根据结果做学习决策。", sourceId: "AI006", factId: "F003" },
      ],
    },
  ],
}
