import type { KnowledgeBase } from "./types"

export const PYTHON_BASIC_KNOWLEDGE_BASE: KnowledgeBase = {
  module: "Python基础",
  version: "0.2.0",
  updatedAt: "2026-07-31",
  sources: ["Python 官方文档", "KnowBalance 自编教学切片"],
  items: [
    {
      sourceId: "K001",
      title: "Python 是什么",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K001_intro.md",
      snippet: "Python 是一种通用编程语言。",
      prerequisites: [],
      keywords: ["Python", "编程", "解释器", "脚本"],
      facts: [{"sourceId": "K001", "factId": "F001", "content": "Python 是一种通用编程语言。", "source_id": "K001", "fact_id": "F001"}, {"sourceId": "K001", "factId": "F002", "content": "Python 程序通常由解释器执行。", "source_id": "K001", "fact_id": "F002"}, {"sourceId": "K001", "factId": "F003", "content": "Python 适合编写脚本、数据处理和教学示例。", "source_id": "K001", "fact_id": "F003"}],
      examples: [{"title": "Python 是什么 基础示例", "code": "print(\"Python 是什么\")\nprint(\"source: K001\")", "explanation": "该示例用于帮助学习者识别“Python 是什么”的基本用途。"}],
      practiceTasks: ["解释 Python 的用途", "运行第一个 Python 程序"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“Python 是什么”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K001", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“Python 是什么”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K001", "factId": "F002"}],
    },
    {
      sourceId: "K002",
      title: "变量与赋值",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K002_variables.md",
      snippet: "Python 使用 = 进行变量赋值。",
      prerequisites: ["K001"],
      keywords: ["变量", "赋值", "variable", "assignment", "保存数据"],
      facts: [{"sourceId": "K002", "factId": "F001", "content": "Python 使用 = 进行变量赋值。", "source_id": "K002", "fact_id": "F001"}, {"sourceId": "K002", "factId": "F002", "content": "变量名用于引用程序中的数据。", "source_id": "K002", "fact_id": "F002"}, {"sourceId": "K002", "factId": "F003", "content": "变量可以被重新赋值，新值会覆盖旧绑定。", "source_id": "K002", "fact_id": "F003"}],
      examples: [{"title": "更新变量值", "code": "age = 18\nage = age + 1\nprint(age)", "explanation": "变量可以先保存旧值，再通过赋值语句更新为新值。"}],
      practiceTasks: ["定义 name、age 两个变量并输出", "判断 x = x + 1 的执行结果"],
      quizItems: [{"level": 1, "type": "choice", "question": "变量赋值在 Python 中使用哪个符号？", "answer": "=", "sourceId": "K002", "factId": "F001", "options": ["=", "==", ":=", "=>"]}, {"level": 2, "type": "practice", "question": "请完成一个与“变量与赋值”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K002", "factId": "F002"}],
    },
    {
      sourceId: "K003",
      title: "基本数据类型",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K003_data_types.md",
      snippet: "int 表示整数，float 表示小数。",
      prerequisites: ["K002"],
      keywords: ["数据类型", "int", "float", "str", "bool", "数字", "字符串"],
      facts: [{"sourceId": "K003", "factId": "F001", "content": "int 表示整数，float 表示小数。", "source_id": "K003", "fact_id": "F001"}, {"sourceId": "K003", "factId": "F002", "content": "str 表示字符串文本。", "source_id": "K003", "fact_id": "F002"}, {"sourceId": "K003", "factId": "F003", "content": "bool 表示 True 或 False 两种逻辑值。", "source_id": "K003", "fact_id": "F003"}],
      examples: [{"title": "识别基础类型", "code": "score = 95\nname = \"Li Hua\"\npassed = True\nprint(type(score), type(name), type(passed))", "explanation": "int、str、bool 表示不同类型的数据，后续运算前应先确认类型。"}],
      practiceTasks: ["区分 3 与 \"3\" 的类型", "写出四种基础类型示例"],
      quizItems: [{"level": 1, "type": "choice", "question": "\"95\" 在 Python 中通常属于哪种类型？", "answer": "str", "sourceId": "K003", "factId": "F001", "options": ["int", "float", "str", "bool"]}, {"level": 2, "type": "practice", "question": "请完成一个与“基本数据类型”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K003", "factId": "F002"}],
    },
    {
      sourceId: "K004",
      title: "输入输出",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K004_input_output.md",
      snippet: "print 用于向屏幕输出内容。",
      prerequisites: ["K002", "K003"],
      keywords: ["input", "print", "输入", "输出", "交互"],
      facts: [{"sourceId": "K004", "factId": "F001", "content": "print 用于向屏幕输出内容。", "source_id": "K004", "fact_id": "F001"}, {"sourceId": "K004", "factId": "F002", "content": "input 用于读取用户输入并返回字符串。", "source_id": "K004", "fact_id": "F002"}, {"sourceId": "K004", "factId": "F003", "content": "需要数值计算时应把 input 结果转换为数字类型。", "source_id": "K004", "fact_id": "F003"}],
      examples: [{"title": "读取姓名并输出问候", "code": "name = input(\"请输入你的姓名：\")\nprint(\"你好，\" + name + \"！欢迎来到Python学习。\")", "explanation": "input 读取用户输入，print 把拼接后的问候语输出到屏幕。"}, {"title": "读取数字并计算和", "code": "a = input(\"请输入第一个数：\")\nb = input(\"请输入第二个数：\")\ntotal = int(a) + int(b)\nprint(\"两数之和为：\", total)", "explanation": "input 返回字符串，int() 转换后才能做算术运算。"}],
      practiceTasks: ["用 input 读取两个数字并计算它们的和", "编写程序：读取用户姓名和年龄，输出格式化的自我介绍"],
      quizItems: [{"level": 1, "type": "choice", "question": "input 函数返回的数据类型是什么？", "answer": "str", "sourceId": "K004", "factId": "F001", "options": ["int", "float", "str", "bool"]}, {"level": 2, "type": "practice", "question": "写一段代码：读取用户输入的两个数字，输出它们的乘积。", "answer": "能正确使用 int() 转换并完成乘法运算。", "sourceId": "K004", "factId": "F003"}],
    },
    {
      sourceId: "K005",
      title: "运算符",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K005_operators.md",
      snippet: "算术运算符可进行加减乘除等计算。",
      prerequisites: ["K003"],
      keywords: ["运算符", "加减乘除", "比较", "逻辑", "operator"],
      facts: [{"sourceId": "K005", "factId": "F001", "content": "算术运算符可进行加减乘除等计算。", "source_id": "K005", "fact_id": "F001"}, {"sourceId": "K005", "factId": "F002", "content": "比较运算符返回布尔值。", "source_id": "K005", "fact_id": "F002"}, {"sourceId": "K005", "factId": "F003", "content": "逻辑运算符 and、or、not 用于组合条件。", "source_id": "K005", "fact_id": "F003"}],
      examples: [{"title": "成绩平均分计算", "code": "score1 = 85\nscore2 = 92\nscore3 = 78\naverage = (score1 + score2 + score3) / 3\nprint(\"平均分：\", average)", "explanation": "算术运算符 + 和 / 用于计算多名学生成绩的平均分。"}, {"title": "判断是否及格", "code": "score = 73\npassed = score >= 60\nprint(\"是否及格：\", passed)\n\nif passed and score < 90:\n    print(\"已通过，可以继续提升。\")", "explanation": "比较运算符 >= 判断分数是否及格，逻辑运算符 and 组合多个条件。"}],
      practiceTasks: ["计算表达式 (85 + 92) / 3 的结果", "编写判断闰年的条件表达式"],
      quizItems: [{"level": 1, "type": "choice", "question": "Python 中 7 // 2 的结果是？", "answer": "3", "sourceId": "K005", "factId": "F001", "options": ["3.5", "3", "4", "报错"]}, {"level": 2, "type": "practice", "question": "写代码判断一个年份是否能被 4 整除且不能被 100 整除。", "answer": "能综合使用取模 % 和逻辑运算符 and。", "sourceId": "K005", "factId": "F003"}],
    },
    {
      sourceId: "K006",
      title: "条件判断",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K006_conditionals.md",
      snippet: "if 根据条件真假决定是否执行代码块。",
      prerequisites: ["K003", "K005"],
      keywords: ["if", "elif", "else", "条件", "判断", "分支"],
      facts: [{"sourceId": "K006", "factId": "F001", "content": "if 根据条件真假决定是否执行代码块。", "source_id": "K006", "fact_id": "F001"}, {"sourceId": "K006", "factId": "F002", "content": "elif 用于追加多个互斥条件分支。", "source_id": "K006", "fact_id": "F002"}, {"sourceId": "K006", "factId": "F003", "content": "else 处理前面条件都不满足的情况。", "source_id": "K006", "fact_id": "F003"}],
      examples: [{"title": "成绩等级判断", "code": "score = 82\nif score >= 60:\n    print(\"pass\")\nelse:\n    print(\"retry\")", "explanation": "if/else 根据条件真假选择不同分支。"}],
      practiceTasks: ["根据分数输出及格或不及格", "写出多分支等级判断"],
      quizItems: [{"level": 1, "type": "choice", "question": "当 if 条件不满足且存在 else 时，程序会执行什么？", "answer": "else 分支", "sourceId": "K006", "factId": "F001", "options": ["if 分支", "else 分支", "两个分支都执行", "程序停止"]}, {"level": 2, "type": "practice", "question": "请完成一个与“条件判断”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K006", "factId": "F002"}],
    },
    {
      sourceId: "K007",
      title: "for 循环",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K007_for_loop.md",
      snippet: "for 循环常用于遍历序列中的元素。",
      prerequisites: ["K002", "K003"],
      keywords: ["for", "循环", "遍历", "重复执行", "序列"],
      facts: [{"sourceId": "K007", "factId": "F001", "content": "for 循环常用于遍历序列中的元素。", "source_id": "K007", "fact_id": "F001"}, {"sourceId": "K007", "factId": "F002", "content": "for 循环适合对列表、字符串等对象逐个处理。", "source_id": "K007", "fact_id": "F002"}, {"sourceId": "K007", "factId": "F003", "content": "range 可生成整数序列配合 for 重复执行固定次数。", "source_id": "K007", "fact_id": "F003"}],
      examples: [{"title": "遍历成绩列表", "code": "scores = [80, 90, 75]\nfor score in scores:\n    print(score)", "explanation": "for 循环会依次取出列表中的每个成绩，适合重复处理。"}],
      practiceTasks: ["遍历列表并打印每个元素", "用 for 计算 1 到 10 的和"],
      quizItems: [{"level": 1, "type": "choice", "question": "for 循环最适合用于什么场景？", "answer": "遍历序列", "sourceId": "K007", "factId": "F001", "options": ["遍历序列", "定义变量", "捕获异常", "导入模块"]}, {"level": 2, "type": "practice", "question": "请完成一个与“for 循环”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K007", "factId": "F002"}],
    },
    {
      sourceId: "K008",
      title: "while 循环",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K008_while_loop.md",
      snippet: "while 会在条件为 True 时重复执行代码块。",
      prerequisites: ["K006"],
      keywords: ["while", "循环", "条件循环", "重复执行"],
      facts: [{"sourceId": "K008", "factId": "F001", "content": "while 会在条件为 True 时重复执行代码块。", "source_id": "K008", "fact_id": "F001"}, {"sourceId": "K008", "factId": "F002", "content": "while 循环必须更新循环条件以避免死循环。", "source_id": "K008", "fact_id": "F002"}, {"sourceId": "K008", "factId": "F003", "content": "while 适合重复次数不确定但停止条件明确的任务。", "source_id": "K008", "fact_id": "F003"}],
      examples: [{"title": "从 1 数到 5", "code": "count = 1\nwhile count <= 5:\n    print(\"第\", count, \"次\")\n    count = count + 1", "explanation": "每次循环把 count 加 1，直到 count > 5 时条件为 False 退出。"}, {"title": "直到输入正确密码", "code": "password = \"\"\nwhile password != \"abc123\":\n    password = input(\"请输入密码：\")\nprint(\"登录成功！\")", "explanation": "循环持续要求输入，直到用户输入正确密码，属于重复次数不确定但终止条件明确的典型场景。"}],
      practiceTasks: ["用 while 实现 1 到 100 累加求和", "写一个猜数字游戏：程序想一个 1-100 的数，用户猜直到猜对"],
      quizItems: [{"level": 1, "type": "choice", "question": "以下哪段代码会导致死循环？", "answer": "x=5; while x>0: print(x)", "sourceId": "K008", "factId": "F002", "options": ["while False: print(1)", "while True: break", "x=0; while x<5: x+=1", "x=5; while x>0: print(x)"]}, {"level": 2, "type": "practice", "question": "用 while 循环计算 1 到 100 的和。", "answer": "能正确使用累计变量并在循环内更新条件变量。", "sourceId": "K008", "factId": "F001"}],
    },
    {
      sourceId: "K009",
      title: "列表",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K009_list.md",
      snippet: "列表可用于保存多个有序元素。",
      prerequisites: ["K002", "K003"],
      keywords: ["列表", "list", "数组", "成绩", "一组数据", "保存多个"],
      facts: [{"sourceId": "K009", "factId": "F001", "content": "列表可用于保存多个有序元素。", "source_id": "K009", "fact_id": "F001"}, {"sourceId": "K009", "factId": "F002", "content": "列表元素可以通过索引访问。", "source_id": "K009", "fact_id": "F002"}, {"sourceId": "K009", "factId": "F003", "content": "append 可向列表末尾添加元素。", "source_id": "K009", "fact_id": "F003"}],
      examples: [{"title": "保存多名学生成绩", "code": "scores = [80, 90, 75]\nscores.append(88)\nprint(scores)", "explanation": "列表适合保存多个有序数据，append 可追加新元素。"}],
      practiceTasks: ["创建成绩列表并计算长度", "向列表追加一个新成绩"],
      quizItems: [{"level": 1, "type": "choice", "question": "向列表末尾添加元素常用哪个方法？", "answer": "append", "sourceId": "K009", "factId": "F001", "options": ["append", "split", "return", "import"]}, {"level": 2, "type": "practice", "question": "请完成一个与“列表”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K009", "factId": "F002"}],
    },
    {
      sourceId: "K010",
      title: "字典",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K010_dict.md",
      snippet: "字典使用键值对保存数据。",
      prerequisites: ["K002", "K003"],
      keywords: ["字典", "dict", "键值对", "姓名", "查成绩", "映射"],
      facts: [{"sourceId": "K010", "factId": "F001", "content": "字典使用键值对保存数据。", "source_id": "K010", "fact_id": "F001"}, {"sourceId": "K010", "factId": "F002", "content": "字典适合根据唯一键快速查找对应值。", "source_id": "K010", "fact_id": "F002"}, {"sourceId": "K010", "factId": "F003", "content": "可以用 dict[key] 访问指定键的值。", "source_id": "K010", "fact_id": "F003"}],
      examples: [{"title": "建立学生成绩字典", "code": "scores = {\"小明\": 92, \"小红\": 85, \"小刚\": 78}\nprint(\"小红的成绩：\", scores[\"小红\"])\nscores[\"小刚\"] = 82\nscores[\"小丽\"] = 95\nprint(\"全部成绩：\", scores)", "explanation": "字典用姓名做键、成绩做值，通过键快速查找对应值。"}, {"title": "遍历字典", "code": "scores = {\"小明\": 92, \"小红\": 85, \"小刚\": 78}\ntotal = 0\nfor name, score in scores.items():\n    print(name, \":\", score)\n    total += score\nprint(\"平均分：\", total / len(scores))", "explanation": ".items() 同时取出键和值，适合批量处理字典内容。"}],
      practiceTasks: ["建立学生姓名到成绩的字典并遍历输出", "使用 .get() 方法安全访问字典，处理不存在的键"],
      quizItems: [{"level": 1, "type": "choice", "question": "访问字典中不存在的键会引发什么错误？", "answer": "KeyError", "sourceId": "K010", "factId": "F003", "options": ["ValueError", "TypeError", "KeyError", "IndexError"]}, {"level": 2, "type": "practice", "question": "给定 scores = {\"小明\": 92, \"小红\": 85}，写代码查找\"小刚\"的成绩，如果不存在输出\"未找到\"。", "answer": "能使用 .get() 或 in 关键字安全访问。", "sourceId": "K010", "factId": "F002"}],
    },
    {
      sourceId: "K011",
      title: "元组与集合",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K011_tuple_set.md",
      snippet: "元组是有序且通常不可变的数据容器。",
      prerequisites: ["K003", "K009"],
      keywords: ["元组", "tuple", "集合", "set", "去重"],
      facts: [{"sourceId": "K011", "factId": "F001", "content": "元组是有序且通常不可变的数据容器。", "source_id": "K011", "fact_id": "F001"}, {"sourceId": "K011", "factId": "F002", "content": "集合用于保存不重复元素。", "source_id": "K011", "fact_id": "F002"}, {"sourceId": "K011", "factId": "F003", "content": "集合适合做去重和成员判断。", "source_id": "K011", "fact_id": "F003"}],
      examples: [{"title": "用元组表示固定坐标", "code": "point = (3, 5)\nx, y = point\nprint(\"坐标：\", x, y)\n# point[0] = 10  # TypeError", "explanation": "元组适合存储不应被修改的固定数据。"}, {"title": "用集合去重", "code": "scores = [85, 92, 85, 78, 92, 85]\nunique_scores = set(scores)\nprint(\"去重后的成绩：\", unique_scores)\n\nif 85 in unique_scores:\n    print(\"有 85 分这个成绩\")", "explanation": "集合自动去除重复元素，适合数据去重和快速成员检查。"}],
      practiceTasks: ["用集合去除姓名列表中的重复项", "说明元组和列表的核心差异（可变性）"],
      quizItems: [{"level": 1, "type": "choice", "question": "以下哪个操作会报错？", "answer": "t=(1,2); t[0]=3", "sourceId": "K011", "factId": "F001", "options": ["t=(1,2); print(t[0])", "t=(1,2); t[0]=3", "s=set([1,2,2]); print(s)", "s={1,2,3}; print(1 in s)"]}, {"level": 2, "type": "practice", "question": "给定 names = [\"小明\",\"小红\",\"小明\",\"小刚\",\"小红\"]，用 set 去重后转为列表输出。", "answer": "能使用 set() 和 list() 完成去重转换。", "sourceId": "K011", "factId": "F002"}],
    },
    {
      sourceId: "K012",
      title: "字符串常用操作",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K012_string.md",
      snippet: "字符串是字符序列。",
      prerequisites: ["K003"],
      keywords: ["字符串", "str", "切片", "split", "join", "文本"],
      facts: [{"sourceId": "K012", "factId": "F001", "content": "字符串是字符序列。", "source_id": "K012", "fact_id": "F001"}, {"sourceId": "K012", "factId": "F002", "content": "split 可按分隔符拆分字符串。", "source_id": "K012", "fact_id": "F002"}, {"sourceId": "K012", "factId": "F003", "content": "join 可把多个字符串连接成一个字符串。", "source_id": "K012", "fact_id": "F003"}],
      examples: [{"title": "拆分和处理成绩数据", "code": "data = \"小明:92,小红:85,小刚:78\"\npairs = data.split(\",\")\nfor pair in pairs:\n    name, score = pair.split(\":\")\n    print(name, \"的成绩是\", score)", "explanation": "split 把逗号分隔的字符串拆成列表，再逐个拆分出姓名和成绩。"}, {"title": "拼接报告", "code": "names = [\"小明\", \"小红\", \"小刚\"]\nscores = [92, 85, 78]\nlines = []\nfor i in range(len(names)):\n    lines.append(names[i] + \"：\" + str(scores[i]) + \"分\")\nreport = \"\\n\".join(lines)\nprint(report)", "explanation": "join 把每行报告用换行符连接成完整的段落文本。"}],
      practiceTasks: ["用 split 和 join 处理并重组 csv 格式数据", "编写程序：把成绩列表用逗号拼接为一行字符串"],
      quizItems: [{"level": 1, "type": "choice", "question": "\"a,b,c\".split(\",\") 的结果是？", "answer": "[\"a\",\"b\",\"c\"]", "sourceId": "K012", "factId": "F002", "options": ["\"abc\"", "[\"a\",\"b\",\"c\"]", "\"a b c\"", "[\"abc\"]"]}, {"level": 2, "type": "practice", "question": "给定 data = \"张三:88,李四:95,王五:72\"，用 split 解析后输出每个同学的姓名和成绩。", "answer": "能使用 split 分步解析字符串。", "sourceId": "K012", "factId": "F002"}],
    },
    {
      sourceId: "K013",
      title: "函数定义与调用",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K013_function.md",
      snippet: "def 用于定义函数。",
      prerequisites: ["K002", "K006", "K007"],
      keywords: ["函数", "def", "调用", "复用", "function"],
      facts: [{"sourceId": "K013", "factId": "F001", "content": "def 用于定义函数。", "source_id": "K013", "fact_id": "F001"}, {"sourceId": "K013", "factId": "F002", "content": "函数把可复用逻辑封装成命名代码块。", "source_id": "K013", "fact_id": "F002"}, {"sourceId": "K013", "factId": "F003", "content": "调用函数时会执行函数体中的代码。", "source_id": "K013", "fact_id": "F003"}],
      examples: [{"title": "封装求平均分函数", "code": "def average(scores):\n    return sum(scores) / len(scores)\nprint(average([80, 90, 75]))", "explanation": "函数把可复用逻辑封装起来，调用时执行函数体。"}],
      practiceTasks: ["定义求和函数", "调用函数输出结果"],
      quizItems: [{"level": 1, "type": "choice", "question": "定义函数使用哪个关键字？", "answer": "def", "sourceId": "K013", "factId": "F001", "options": ["def", "for", "if", "class"]}, {"level": 2, "type": "practice", "question": "请完成一个与“函数定义与调用”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K013", "factId": "F002"}],
    },
    {
      sourceId: "K014",
      title: "参数与返回值",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K014_params_return.md",
      snippet: "参数用于把外部数据传入函数。",
      prerequisites: ["K013"],
      keywords: ["参数", "返回值", "return", "函数输入", "函数输出"],
      facts: [{"sourceId": "K014", "factId": "F001", "content": "参数用于把外部数据传入函数。", "source_id": "K014", "fact_id": "F001"}, {"sourceId": "K014", "factId": "F002", "content": "return 用于把函数结果返回给调用者。", "source_id": "K014", "fact_id": "F002"}, {"sourceId": "K014", "factId": "F003", "content": "没有显式 return 的函数默认返回 None。", "source_id": "K014", "fact_id": "F003"}],
      examples: [{"title": "带参数和返回值的成绩处理函数", "code": "def calc_average(scores):\n    total = sum(scores)\n    count = len(scores)\n    return total / count\n\ndef get_grade(score):\n    if score >= 90:\n        return \"优秀\"\n    elif score >= 60:\n        return \"及格\"\n    else:\n        return \"不及格\"\n\navg = calc_average([85, 92, 78, 95])\nprint(\"平均分：\", avg)\nprint(\"等级：\", get_grade(avg))", "explanation": "calc_average 接收成绩列表为参数，return 返回平均分；get_grade 根据分数返回等级。"}, {"title": "无 return 的函数", "code": "def show_info(name, score):\n    print(name + \"的成绩是：\" + str(score))\n\nresult = show_info(\"小明\", 92)\nprint(\"返回值：\", result)", "explanation": "没有 return 语句的函数默认返回 None。"}],
      practiceTasks: ["写一个带参数的求和函数并返回值", "写一个函数接收成绩列表返回最高分和最低分"],
      quizItems: [{"level": 1, "type": "choice", "question": "函数没有写 return 语句时，调用后得到什么？", "answer": "None", "sourceId": "K014", "factId": "F003", "options": ["None", "0", "报错", "最后一个表达式的值"]}, {"level": 2, "type": "practice", "question": "写一个函数 calc(scores)，接收成绩列表，返回最高分、最低分和平均分三个值。", "answer": "能使用 return 返回多个值（元组）。", "sourceId": "K014", "factId": "F002"}],
    },
    {
      sourceId: "K015",
      title: "文件读写",
      module: "Python基础",
      difficulty: "intermediate",
      file: "knowledge_base/python_basic/K015_file_io.md",
      snippet: "open 可用于打开文件。",
      prerequisites: ["K003", "K012"],
      keywords: ["文件", "读取", "写入", "open", "read", "write", "文本文件"],
      facts: [{"sourceId": "K015", "factId": "F001", "content": "open 可用于打开文件。", "source_id": "K015", "fact_id": "F001"}, {"sourceId": "K015", "factId": "F002", "content": "read 可读取文件内容。", "source_id": "K015", "fact_id": "F002"}, {"sourceId": "K015", "factId": "F003", "content": "写文件时应明确写入模式并注意覆盖风险。", "source_id": "K015", "fact_id": "F003"}],
      examples: [{"title": "读取成绩文件", "code": "with open(\"scores.txt\", \"r\", encoding=\"utf-8\") as f:\n    content = f.read()\n    print(\"文件内容：\")\n    print(content)", "explanation": "with 语句自动管理文件关闭，read() 一次性读取全部内容。"}, {"title": "写入统计结果", "code": "students = [\"小明:92\", \"小红:85\", \"小刚:78\"]\nwith open(\"report.txt\", \"w\", encoding=\"utf-8\") as f:\n    for student in students:\n        f.write(student + \"\\n\")\nprint(\"报告已写入 report.txt\")", "explanation": "\"w\" 写入模式会覆盖已有文件；每次 write 写入一行，需手动加换行符。"}],
      practiceTasks: ["读取文本文件内容并统计行数", "把学生成绩逐行写入文件"],
      quizItems: [{"level": 1, "type": "choice", "question": "使用 open 的 \"w\" 模式打开一个已有文件会？", "answer": "覆盖原文件", "sourceId": "K015", "factId": "F003", "options": ["追加内容", "覆盖原文件", "报错", "只读打开"]}, {"level": 2, "type": "practice", "question": "写代码：把程序中的学生姓名和成绩逐行写入 score_report.txt，每行格式为\"姓名：成绩\"。", "answer": "能用 with + write 完成文件写入。", "sourceId": "K015", "factId": "F001"}],
    },
    {
      sourceId: "K016",
      title: "异常处理",
      module: "Python基础",
      difficulty: "intermediate",
      file: "knowledge_base/python_basic/K016_exception.md",
      snippet: "try/except 用于捕获并处理运行时异常。",
      prerequisites: ["K006"],
      keywords: ["异常", "报错", "try", "except", "错误处理"],
      facts: [{"sourceId": "K016", "factId": "F001", "content": "try/except 用于捕获并处理运行时异常。", "source_id": "K016", "fact_id": "F001"}, {"sourceId": "K016", "factId": "F002", "content": "异常处理可以避免程序因可预期错误直接终止。", "source_id": "K016", "fact_id": "F002"}, {"sourceId": "K016", "factId": "F003", "content": "except 分支应针对具体错误给出处理逻辑。", "source_id": "K016", "fact_id": "F003"}],
      examples: [{"title": "处理数字转换异常", "code": "user_input = input(\"请输入成绩：\")\ntry:\n    score = int(user_input)\n    if score >= 60:\n        print(\"及格\")\n    else:\n        print(\"不及格\")\nexcept ValueError:\n    print(\"输入无效，请输入数字。\")", "explanation": "当用户输入非数字字符串时，int() 抛出 ValueError，被 except 捕获后给出友好提示。"}, {"title": "处理文件操作异常", "code": "filename = input(\"请输入文件名：\")\ntry:\n    with open(filename, \"r\", encoding=\"utf-8\") as f:\n        print(f.read())\nexcept FileNotFoundError:\n    print(\"文件不存在，请检查文件名。\")\nexcept PermissionError:\n    print(\"没有权限读取该文件。\")", "explanation": "针对不同类型的异常分别处理，比捕获所有异常更精确。"}],
      practiceTasks: ["用 try/except 处理数字转换和除零错误", "写一个 safe_divide(a, b) 函数处理除零异常"],
      quizItems: [{"level": 1, "type": "choice", "question": "如果 try 块中没有抛出异常，except 块会执行吗？", "answer": "不会", "sourceId": "K016", "factId": "F001", "options": ["会", "不会", "看情况", "报错"]}, {"level": 2, "type": "practice", "question": "写一个 safe_divide(a, b) 函数，返回 a/b 的结果，如果 b 为 0 则返回\"除数不能为0\"。", "answer": "能用 try/except 捕获 ZeroDivisionError。", "sourceId": "K016", "factId": "F002"}],
    },
    {
      sourceId: "K017",
      title: "模块导入",
      module: "Python基础",
      difficulty: "intermediate",
      file: "knowledge_base/python_basic/K017_import.md",
      snippet: "import 用于导入模块。",
      prerequisites: ["K013"],
      keywords: ["import", "模块", "导入", "库", "复用代码"],
      facts: [{"sourceId": "K017", "factId": "F001", "content": "import 用于导入模块。", "source_id": "K017", "fact_id": "F001"}, {"sourceId": "K017", "factId": "F002", "content": "模块可以复用其他文件或标准库中的功能。", "source_id": "K017", "fact_id": "F002"}, {"sourceId": "K017", "factId": "F003", "content": "from ... import ... 可导入模块中的指定对象。", "source_id": "K017", "fact_id": "F003"}],
      examples: [{"title": "用 math 模块计算统计值", "code": "import math\n\nscores = [85, 92, 78, 95, 88]\nmean = sum(scores) / len(scores)\nstd_dev = math.sqrt(sum((x - mean) ** 2 for x in scores) / len(scores))\nprint(\"平均分：\", round(mean, 2))\nprint(\"标准差：\", round(std_dev, 2))", "explanation": "import math 导入整个 math 模块，math.sqrt 使用其中的平方根函数。"}, {"title": "从模块导入指定函数", "code": "from math import sqrt, pi\n\nr = 5\narea = pi * r ** 2\nprint(\"半径为\", r, \"的圆面积：\", round(area, 2))\n\nresult = sqrt(144)\nprint(\"144 的平方根：\", result)", "explanation": "from ... import ... 只导入需要的函数或常量，调用时无需加模块前缀。"}],
      practiceTasks: ["导入 random 模块生成随机数", "使用 math 模块计算圆周长和面积"],
      quizItems: [{"level": 1, "type": "choice", "question": "以下哪种方式导入后可以直接调用 sqrt(9) 而不需要写 math.sqrt(9)？", "answer": "from math import sqrt", "sourceId": "K017", "factId": "F003", "options": ["import math", "from math import sqrt", "include math", "import *"]}, {"level": 2, "type": "practice", "question": "导入 random 模块，写代码生成 5 个 1 到 100 之间的随机整数并输出。", "answer": "能正确使用 random.randint()。", "sourceId": "K017", "factId": "F002"}],
    },
    {
      sourceId: "K018",
      title: "成绩统计器综合项目",
      module: "Python基础",
      difficulty: "integrated",
      file: "knowledge_base/python_basic/K018_score_project.md",
      snippet: "成绩统计项目可综合练习列表、循环和函数。",
      prerequisites: ["K007", "K009", "K013"],
      keywords: ["成绩统计", "综合项目", "循环", "列表", "函数", "平均分"],
      facts: [{"sourceId": "K018", "factId": "F001", "content": "成绩统计项目可综合练习列表、循环和函数。", "source_id": "K018", "fact_id": "F001"}, {"sourceId": "K018", "factId": "F002", "content": "成绩列表可以用 for 循环逐项累计求和。", "source_id": "K018", "fact_id": "F002"}, {"sourceId": "K018", "factId": "F003", "content": "把统计逻辑封装为函数可提升复用性。", "source_id": "K018", "fact_id": "F003"}],
      examples: [{"title": "成绩统计器最小项目", "code": "def average(scores):\n    return sum(scores) / len(scores)\n\nscores = [80, 90, 75]\nprint(max(scores), min(scores), average(scores))", "explanation": "成绩统计项目把列表、循环/聚合和函数组合成完整任务。"}],
      practiceTasks: ["实现成绩平均分函数", "输出最高分、最低分和平均分"],
      quizItems: [{"level": 1, "type": "short", "question": "成绩统计器综合项目通常至少组合哪些知识？", "answer": "列表、循环和函数", "sourceId": "K018", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“成绩统计器综合项目”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K018", "factId": "F002"}],
    },
  ],
}
