import type { KnowledgeBase } from "./types"

export const PYTHON_BASIC_KNOWLEDGE_BASE: KnowledgeBase = {
  module: "Python基础",
  version: "0.1.0",
  updatedAt: "2026-07-17",
  sources: ["Python 官方文档", "KnowBalance 自编教学切片"],
  items: [
    {
      sourceId: "K001",
      title: "Python 是什么",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K001_intro.md",
      snippet: "Python 是一种通用编程语言。",
      prerequisites: [],
      keywords: ["Python", "编程", "解释器", "脚本"],
      facts: [{"sourceId": "K001", "factId": "F001", "content": "Python 是一种通用编程语言。", "source_id": "K001", "fact_id": "F001"}, {"sourceId": "K001", "factId": "F002", "content": "Python 程序通常由解释器执行。", "source_id": "K001", "fact_id": "F002"}, {"sourceId": "K001", "factId": "F003", "content": "Python 适合编写脚本、数据处理和教学示例。", "source_id": "K001", "fact_id": "F003"}],
      examples: [{"title": "Python 是什么 基础示例", "code": "print(\"Python 是什么\")\nprint(\"source: K001\")", "explanation": "该示例用于帮助学习者识别“Python 是什么”的基本用途。"}],
      practiceTasks: ["解释 Python 的用途", "运行第一个 Python 程序"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“Python 是什么”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K001", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“Python 是什么”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K001", "factId": "F002"}],
    },
    {
      sourceId: "K002",
      title: "变量与赋值",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K002_variables.md",
      snippet: "Python 使用 = 进行变量赋值。",
      prerequisites: ["K001"],
      keywords: ["变量", "赋值", "variable", "assignment", "保存数据"],
      facts: [{"sourceId": "K002", "factId": "F001", "content": "Python 使用 = 进行变量赋值。", "source_id": "K002", "fact_id": "F001"}, {"sourceId": "K002", "factId": "F002", "content": "变量名用于引用程序中的数据。", "source_id": "K002", "fact_id": "F002"}, {"sourceId": "K002", "factId": "F003", "content": "变量可以被重新赋值，新值会覆盖旧绑定。", "source_id": "K002", "fact_id": "F003"}],
      examples: [{"title": "更新变量值", "code": "age = 18\nage = age + 1\nprint(age)", "explanation": "变量可以先保存旧值，再通过赋值语句更新为新值。"}],
      practiceTasks: ["定义 name、age 两个变量并输出", "判断 x = x + 1 的执行结果"],
      quizItems: [{"level": 1, "type": "choice", "question": "变量赋值在 Python 中使用哪个符号？", "answer": "=", "sourceId": "K002", "factId": "F001", "options": ["=", "==", ":=", "=>"]}, {"level": 2, "type": "practice", "question": "请完成一个与“变量与赋值”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K002", "factId": "F002"}],
    },
    {
      sourceId: "K003",
      title: "基本数据类型",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K003_data_types.md",
      snippet: "int 表示整数，float 表示小数。",
      prerequisites: ["K002"],
      keywords: ["数据类型", "int", "float", "str", "bool", "数字", "字符串"],
      facts: [{"sourceId": "K003", "factId": "F001", "content": "int 表示整数，float 表示小数。", "source_id": "K003", "fact_id": "F001"}, {"sourceId": "K003", "factId": "F002", "content": "str 表示字符串文本。", "source_id": "K003", "fact_id": "F002"}, {"sourceId": "K003", "factId": "F003", "content": "bool 表示 True 或 False 两种逻辑值。", "source_id": "K003", "fact_id": "F003"}],
      examples: [{"title": "识别基础类型", "code": "score = 95\nname = \"Li Hua\"\npassed = True\nprint(type(score), type(name), type(passed))", "explanation": "int、str、bool 表示不同类型的数据，后续运算前应先确认类型。"}],
      practiceTasks: ["区分 3 与 \"3\" 的类型", "写出四种基础类型示例"],
      quizItems: [{"level": 1, "type": "choice", "question": "\"95\" 在 Python 中通常属于哪种类型？", "answer": "str", "sourceId": "K003", "factId": "F001", "options": ["int", "float", "str", "bool"]}, {"level": 2, "type": "practice", "question": "请完成一个与“基本数据类型”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K003", "factId": "F002"}],
    },
    {
      sourceId: "K004",
      title: "输入输出",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K004_input_output.md",
      snippet: "print 用于向屏幕输出内容。",
      prerequisites: ["K002", "K003"],
      keywords: ["input", "print", "输入", "输出", "交互"],
      facts: [{"sourceId": "K004", "factId": "F001", "content": "print 用于向屏幕输出内容。", "source_id": "K004", "fact_id": "F001"}, {"sourceId": "K004", "factId": "F002", "content": "input 用于读取用户输入并返回字符串。", "source_id": "K004", "fact_id": "F002"}, {"sourceId": "K004", "factId": "F003", "content": "需要数值计算时应把 input 结果转换为数字类型。", "source_id": "K004", "fact_id": "F003"}],
      examples: [{"title": "输入输出 基础示例", "code": "print(\"输入输出\")\nprint(\"source: K004\")", "explanation": "该示例用于帮助学习者识别“输入输出”的基本用途。"}],
      practiceTasks: ["读取姓名并输出欢迎语", "读取两个数字并输出和"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“输入输出”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K004", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“输入输出”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K004", "factId": "F002"}],
    },
    {
      sourceId: "K005",
      title: "运算符",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K005_operators.md",
      snippet: "算术运算符可进行加减乘除等计算。",
      prerequisites: ["K003"],
      keywords: ["运算符", "加减乘除", "比较", "逻辑", "operator"],
      facts: [{"sourceId": "K005", "factId": "F001", "content": "算术运算符可进行加减乘除等计算。", "source_id": "K005", "fact_id": "F001"}, {"sourceId": "K005", "factId": "F002", "content": "比较运算符返回布尔值。", "source_id": "K005", "fact_id": "F002"}, {"sourceId": "K005", "factId": "F003", "content": "逻辑运算符 and、or、not 用于组合条件。", "source_id": "K005", "fact_id": "F003"}],
      examples: [{"title": "运算符 基础示例", "code": "print(\"运算符\")\nprint(\"source: K005\")", "explanation": "该示例用于帮助学习者识别“运算符”的基本用途。"}],
      practiceTasks: ["计算表达式结果", "判断比较表达式真假"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“运算符”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K005", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“运算符”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K005", "factId": "F002"}],
    },
    {
      sourceId: "K006",
      title: "条件判断",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K006_conditionals.md",
      snippet: "if 根据条件真假决定是否执行代码块。",
      prerequisites: ["K003", "K005"],
      keywords: ["if", "elif", "else", "条件", "判断", "分支"],
      facts: [{"sourceId": "K006", "factId": "F001", "content": "if 根据条件真假决定是否执行代码块。", "source_id": "K006", "fact_id": "F001"}, {"sourceId": "K006", "factId": "F002", "content": "elif 用于追加多个互斥条件分支。", "source_id": "K006", "fact_id": "F002"}, {"sourceId": "K006", "factId": "F003", "content": "else 处理前面条件都不满足的情况。", "source_id": "K006", "fact_id": "F003"}],
      examples: [{"title": "成绩等级判断", "code": "score = 82\nif score >= 60:\n    print(\"pass\")\nelse:\n    print(\"retry\")", "explanation": "if/else 根据条件真假选择不同分支。"}],
      practiceTasks: ["根据分数输出及格或不及格", "写出多分支等级判断"],
      quizItems: [{"level": 1, "type": "choice", "question": "当 if 条件不满足且存在 else 时，程序会执行什么？", "answer": "else 分支", "sourceId": "K006", "factId": "F001", "options": ["if 分支", "else 分支", "两个分支都执行", "程序停止"]}, {"level": 2, "type": "practice", "question": "请完成一个与“条件判断”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K006", "factId": "F002"}],
    },
    {
      sourceId: "K007",
      title: "for 循环",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K007_for_loop.md",
      snippet: "for 循环常用于遍历序列中的元素。",
      prerequisites: ["K002", "K003"],
      keywords: ["for", "循环", "遍历", "重复执行", "序列"],
      facts: [{"sourceId": "K007", "factId": "F001", "content": "for 循环常用于遍历序列中的元素。", "source_id": "K007", "fact_id": "F001"}, {"sourceId": "K007", "factId": "F002", "content": "for 循环适合对列表、字符串等对象逐个处理。", "source_id": "K007", "fact_id": "F002"}, {"sourceId": "K007", "factId": "F003", "content": "range 可生成整数序列配合 for 重复执行固定次数。", "source_id": "K007", "fact_id": "F003"}],
      examples: [{"title": "遍历成绩列表", "code": "scores = [80, 90, 75]\nfor score in scores:\n    print(score)", "explanation": "for 循环会依次取出列表中的每个成绩，适合重复处理。"}],
      practiceTasks: ["遍历列表并打印每个元素", "用 for 计算 1 到 10 的和"],
      quizItems: [{"level": 1, "type": "choice", "question": "for 循环最适合用于什么场景？", "answer": "遍历序列", "sourceId": "K007", "factId": "F001", "options": ["遍历序列", "定义变量", "捕获异常", "导入模块"]}, {"level": 2, "type": "practice", "question": "请完成一个与“for 循环”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K007", "factId": "F002"}],
    },
    {
      sourceId: "K008",
      title: "while 循环",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K008_while_loop.md",
      snippet: "while 会在条件为 True 时重复执行代码块。",
      prerequisites: ["K006"],
      keywords: ["while", "循环", "条件循环", "重复执行"],
      facts: [{"sourceId": "K008", "factId": "F001", "content": "while 会在条件为 True 时重复执行代码块。", "source_id": "K008", "fact_id": "F001"}, {"sourceId": "K008", "factId": "F002", "content": "while 循环必须更新循环条件以避免死循环。", "source_id": "K008", "fact_id": "F002"}, {"sourceId": "K008", "factId": "F003", "content": "while 适合重复次数不确定但停止条件明确的任务。", "source_id": "K008", "fact_id": "F003"}],
      examples: [{"title": "while 循环 基础示例", "code": "print(\"while 循环\")\nprint(\"source: K008\")", "explanation": "该示例用于帮助学习者识别“while 循环”的基本用途。"}],
      practiceTasks: ["用 while 从 1 打印到 5", "说明死循环产生原因"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“while 循环”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K008", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“while 循环”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K008", "factId": "F002"}],
    },
    {
      sourceId: "K009",
      title: "列表",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K009_list.md",
      snippet: "列表可用于保存多个有序元素。",
      prerequisites: ["K002", "K003"],
      keywords: ["列表", "list", "数组", "成绩", "一组数据", "保存多个"],
      facts: [{"sourceId": "K009", "factId": "F001", "content": "列表可用于保存多个有序元素。", "source_id": "K009", "fact_id": "F001"}, {"sourceId": "K009", "factId": "F002", "content": "列表元素可以通过索引访问。", "source_id": "K009", "fact_id": "F002"}, {"sourceId": "K009", "factId": "F003", "content": "append 可向列表末尾添加元素。", "source_id": "K009", "fact_id": "F003"}],
      examples: [{"title": "保存多名学生成绩", "code": "scores = [80, 90, 75]\nscores.append(88)\nprint(scores)", "explanation": "列表适合保存多个有序数据，append 可追加新元素。"}],
      practiceTasks: ["创建成绩列表并计算长度", "向列表追加一个新成绩"],
      quizItems: [{"level": 1, "type": "choice", "question": "向列表末尾添加元素常用哪个方法？", "answer": "append", "sourceId": "K009", "factId": "F001", "options": ["append", "split", "return", "import"]}, {"level": 2, "type": "practice", "question": "请完成一个与“列表”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K009", "factId": "F002"}],
    },
    {
      sourceId: "K010",
      title: "字典",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K010_dict.md",
      snippet: "字典使用键值对保存数据。",
      prerequisites: ["K002", "K003"],
      keywords: ["字典", "dict", "键值对", "姓名", "查成绩", "映射"],
      facts: [{"sourceId": "K010", "factId": "F001", "content": "字典使用键值对保存数据。", "source_id": "K010", "fact_id": "F001"}, {"sourceId": "K010", "factId": "F002", "content": "字典适合根据唯一键快速查找对应值。", "source_id": "K010", "fact_id": "F002"}, {"sourceId": "K010", "factId": "F003", "content": "可以用 dict[key] 访问指定键的值。", "source_id": "K010", "fact_id": "F003"}],
      examples: [{"title": "字典 基础示例", "code": "print(\"字典\")\nprint(\"source: K010\")", "explanation": "该示例用于帮助学习者识别“字典”的基本用途。"}],
      practiceTasks: ["建立姓名到成绩的字典", "根据姓名查询成绩"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“字典”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K010", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“字典”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K010", "factId": "F002"}],
    },
    {
      sourceId: "K011",
      title: "元组与集合",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K011_tuple_set.md",
      snippet: "元组是有序且通常不可变的数据容器。",
      prerequisites: ["K003", "K009"],
      keywords: ["元组", "tuple", "集合", "set", "去重"],
      facts: [{"sourceId": "K011", "factId": "F001", "content": "元组是有序且通常不可变的数据容器。", "source_id": "K011", "fact_id": "F001"}, {"sourceId": "K011", "factId": "F002", "content": "集合用于保存不重复元素。", "source_id": "K011", "fact_id": "F002"}, {"sourceId": "K011", "factId": "F003", "content": "集合适合做去重和成员判断。", "source_id": "K011", "fact_id": "F003"}],
      examples: [{"title": "元组与集合 基础示例", "code": "print(\"元组与集合\")\nprint(\"source: K011\")", "explanation": "该示例用于帮助学习者识别“元组与集合”的基本用途。"}],
      practiceTasks: ["用集合去除重复姓名", "说明元组和列表差异"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“元组与集合”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K011", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“元组与集合”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K011", "factId": "F002"}],
    },
    {
      sourceId: "K012",
      title: "字符串常用操作",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K012_string.md",
      snippet: "字符串是字符序列。",
      prerequisites: ["K003"],
      keywords: ["字符串", "str", "切片", "split", "join", "文本"],
      facts: [{"sourceId": "K012", "factId": "F001", "content": "字符串是字符序列。", "source_id": "K012", "fact_id": "F001"}, {"sourceId": "K012", "factId": "F002", "content": "split 可按分隔符拆分字符串。", "source_id": "K012", "fact_id": "F002"}, {"sourceId": "K012", "factId": "F003", "content": "join 可把多个字符串连接成一个字符串。", "source_id": "K012", "fact_id": "F003"}],
      examples: [{"title": "字符串常用操作 基础示例", "code": "print(\"字符串常用操作\")\nprint(\"source: K012\")", "explanation": "该示例用于帮助学习者识别“字符串常用操作”的基本用途。"}],
      practiceTasks: ["拆分逗号分隔成绩", "拼接一行报告文本"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“字符串常用操作”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K012", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“字符串常用操作”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K012", "factId": "F002"}],
    },
    {
      sourceId: "K013",
      title: "函数定义与调用",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K013_function.md",
      snippet: "def 用于定义函数。",
      prerequisites: ["K002", "K006", "K007"],
      keywords: ["函数", "def", "调用", "复用", "function"],
      facts: [{"sourceId": "K013", "factId": "F001", "content": "def 用于定义函数。", "source_id": "K013", "fact_id": "F001"}, {"sourceId": "K013", "factId": "F002", "content": "函数把可复用逻辑封装成命名代码块。", "source_id": "K013", "fact_id": "F002"}, {"sourceId": "K013", "factId": "F003", "content": "调用函数时会执行函数体中的代码。", "source_id": "K013", "fact_id": "F003"}],
      examples: [{"title": "封装求平均分函数", "code": "def average(scores):\n    return sum(scores) / len(scores)\nprint(average([80, 90, 75]))", "explanation": "函数把可复用逻辑封装起来，调用时执行函数体。"}],
      practiceTasks: ["定义求和函数", "调用函数输出结果"],
      quizItems: [{"level": 1, "type": "choice", "question": "定义函数使用哪个关键字？", "answer": "def", "sourceId": "K013", "factId": "F001", "options": ["def", "for", "if", "class"]}, {"level": 2, "type": "practice", "question": "请完成一个与“函数定义与调用”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K013", "factId": "F002"}],
    },
    {
      sourceId: "K014",
      title: "参数与返回值",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K014_params_return.md",
      snippet: "参数用于把外部数据传入函数。",
      prerequisites: ["K013"],
      keywords: ["参数", "返回值", "return", "函数输入", "函数输出"],
      facts: [{"sourceId": "K014", "factId": "F001", "content": "参数用于把外部数据传入函数。", "source_id": "K014", "fact_id": "F001"}, {"sourceId": "K014", "factId": "F002", "content": "return 用于把函数结果返回给调用者。", "source_id": "K014", "fact_id": "F002"}, {"sourceId": "K014", "factId": "F003", "content": "没有显式 return 的函数默认返回 None。", "source_id": "K014", "fact_id": "F003"}],
      examples: [{"title": "参数与返回值 基础示例", "code": "print(\"参数与返回值\")\nprint(\"source: K014\")", "explanation": "该示例用于帮助学习者识别“参数与返回值”的基本用途。"}],
      practiceTasks: ["写一个带参数的平均值函数", "判断函数返回值"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“参数与返回值”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K014", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“参数与返回值”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K014", "factId": "F002"}],
    },
    {
      sourceId: "K015",
      title: "文件读写",
      module: "Python基础",
      difficulty: "intermediate",
      file: "knowledge_base/python_basic/K015_file_io.md",
      snippet: "open 可用于打开文件。",
      prerequisites: ["K003", "K012"],
      keywords: ["文件", "读取", "写入", "open", "read", "write", "文本文件"],
      facts: [{"sourceId": "K015", "factId": "F001", "content": "open 可用于打开文件。", "source_id": "K015", "fact_id": "F001"}, {"sourceId": "K015", "factId": "F002", "content": "read 可读取文件内容。", "source_id": "K015", "fact_id": "F002"}, {"sourceId": "K015", "factId": "F003", "content": "写文件时应明确写入模式并注意覆盖风险。", "source_id": "K015", "fact_id": "F003"}],
      examples: [{"title": "文件读写 基础示例", "code": "print(\"文件读写\")\nprint(\"source: K015\")", "explanation": "该示例用于帮助学习者识别“文件读写”的基本用途。"}],
      practiceTasks: ["读取文本文件内容", "把统计结果写入文件"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“文件读写”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K015", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“文件读写”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K015", "factId": "F002"}],
    },
    {
      sourceId: "K016",
      title: "异常处理",
      module: "Python基础",
      difficulty: "intermediate",
      file: "knowledge_base/python_basic/K016_exception.md",
      snippet: "try/except 用于捕获并处理运行时异常。",
      prerequisites: ["K006"],
      keywords: ["异常", "报错", "try", "except", "错误处理"],
      facts: [{"sourceId": "K016", "factId": "F001", "content": "try/except 用于捕获并处理运行时异常。", "source_id": "K016", "fact_id": "F001"}, {"sourceId": "K016", "factId": "F002", "content": "异常处理可以避免程序因可预期错误直接终止。", "source_id": "K016", "fact_id": "F002"}, {"sourceId": "K016", "factId": "F003", "content": "except 分支应针对具体错误给出处理逻辑。", "source_id": "K016", "fact_id": "F003"}],
      examples: [{"title": "异常处理 基础示例", "code": "print(\"异常处理\")\nprint(\"source: K016\")", "explanation": "该示例用于帮助学习者识别“异常处理”的基本用途。"}],
      practiceTasks: ["处理数字转换错误", "解释 try/except 执行流程"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“异常处理”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K016", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“异常处理”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K016", "factId": "F002"}],
    },
    {
      sourceId: "K017",
      title: "模块导入",
      module: "Python基础",
      difficulty: "intermediate",
      file: "knowledge_base/python_basic/K017_import.md",
      snippet: "import 用于导入模块。",
      prerequisites: ["K013"],
      keywords: ["import", "模块", "导入", "库", "复用代码"],
      facts: [{"sourceId": "K017", "factId": "F001", "content": "import 用于导入模块。", "source_id": "K017", "fact_id": "F001"}, {"sourceId": "K017", "factId": "F002", "content": "模块可以复用其他文件或标准库中的功能。", "source_id": "K017", "fact_id": "F002"}, {"sourceId": "K017", "factId": "F003", "content": "from ... import ... 可导入模块中的指定对象。", "source_id": "K017", "fact_id": "F003"}],
      examples: [{"title": "模块导入 基础示例", "code": "print(\"模块导入\")\nprint(\"source: K017\")", "explanation": "该示例用于帮助学习者识别“模块导入”的基本用途。"}],
      practiceTasks: ["导入 math 并使用 sqrt", "比较 import 和 from import"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“模块导入”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K017", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“模块导入”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K017", "factId": "F002"}],
    },
    {
      sourceId: "K018",
      title: "成绩统计器综合项目",
      module: "Python基础",
      difficulty: "integrated",
      file: "knowledge_base/python_basic/K018_score_project.md",
      snippet: "成绩统计项目可综合练习列表、循环和函数。",
      prerequisites: ["K007", "K009", "K013"],
      keywords: ["成绩统计", "综合项目", "循环", "列表", "函数", "平均分"],
      facts: [{"sourceId": "K018", "factId": "F001", "content": "成绩统计项目可综合练习列表、循环和函数。", "source_id": "K018", "fact_id": "F001"}, {"sourceId": "K018", "factId": "F002", "content": "成绩列表可以用 for 循环逐项累计求和。", "source_id": "K018", "fact_id": "F002"}, {"sourceId": "K018", "factId": "F003", "content": "把统计逻辑封装为函数可提升复用性。", "source_id": "K018", "fact_id": "F003"}],
      examples: [{"title": "成绩统计器最小项目", "code": "def average(scores):\n    return sum(scores) / len(scores)\n\nscores = [80, 90, 75]\nprint(max(scores), min(scores), average(scores))", "explanation": "成绩统计项目把列表、循环/聚合和函数组合成完整任务。"}],
      practiceTasks: ["实现成绩平均分函数", "输出最高分、最低分和平均分"],
      quizItems: [{"level": 1, "type": "short", "question": "成绩统计器综合项目通常至少组合哪些知识？", "answer": "列表、循环和函数", "sourceId": "K018", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“成绩统计器综合项目”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K018", "factId": "F002"}],
    },
  ],
}
